version: "3"

services:
    mc:
        container_name: mc1.12.2
        image: itzg/minecraft-server:java8
        ports:
            - 25565:25565
        environment:
            - EULA=TRUE
            - VERSION=1.12.2
            - TYPE=FORGE
            - FORGE_VERSION=14.23.5.2854
        tty: true
        stdin_open: true
        restart: unless-stopped
        volumes:
            # attach a directory relative to the directory containing this compose file
            - ./minecraft-data-1.12.2:/data

    mc1:
        container_name: mc1.18
        image: itzg/minecraft-server
        ports:
            - 25566:25565
        environment:
            - EULA=TRUE
            - VERSION=1.18
        tty: true
        stdin_open: true
        restart: unless-stopped
        volumes:
            # attach a directory relative to the directory containing this compose file
            - ./minecraft-data-1.18:/data